### ISSUE TITLE
The first time it shows menu event won't be fired

### ISSUE THREAD

**Issue by qiulang** [maicki/MISDropdownViewController#1]
[self.dropdownMenuView addTarget:self action:@selector(dropMenuChanged:) forControlEvents:UIControlEventValueChanged];

The first time it shows dropMenuChanged: won't be fired. I briefly check the code and it seems that backgroundOverlay handle the touch event so tableview wasn't able to get the touch event

**Comment by maicki** [comment]
This is expected behavior as the initial selected item index is always 0. As soon as another row is selected the UIControlEventValueChange will be fired.

**Comment by qiulang** [comment]
The problem is that the first time it shows and another row is selected there is no event for it. So I have  to show it again to make my selection take effect.

**Comment by vj-narola** [comment]
I'm facing the same issue as faced by @qiulang . Can you please help me solve this issue ?

**Comment by maicki** [comment]
@qiulang The initial selected item index will always be 0 if there are rows available. If you change it in code (via selectedItemIndex) there will be no actions send to be consistent with all other controls on iOS. The idea is that the action should only fired automatically as a result of user interaction. See also the discussion around UISegmentedControl behavior that changed from iOS 4 to iOS 5: http://stackoverflow.com/questions/8054728/uisegmentedcontrol-change-event-not-firing-in-ios5 Does that answer your problem?

@vj-narola What is your exact problem? Maybe the answer above helps ...
